spring:
  data:
    neo4j:
      uri: bolt://localhost
      username: neo4j
      password: 123456
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true  #设置开启热部署
server:
  port: 8081